import time

cash = 0

def start():
    global player_name
    print("Starting Chapter 2...")
    time.sleep(2)

    print("Press F to go outside.")
    user_input = input("Press F to continue: ")
    if user_input == "F":
        print("You step outside the house")
        time.sleep(2)
        print("It's a sunny afternoon so you see a lot of people in the street walking around..")
        time.sleep(2)
        print("In the distance, you see a familar face in the crowd")
        time.sleep(2)
        print("It's your grandma's neighbor, Ms. Qulsum")
        time.sleep(2)
        print("Approach her?")
        user_input = input("Press Y to approach Ms. Qulsum: ")

        if user_input == "Y":
            print("You approach Ms. Qulsum")
            time.sleep(2)
            print("[Qulsum]: Hello sir, how are you? How is your grandma?")
            time.sleep(2)
            print("[You]: I am good, but my grandma is missing! I believe she is lost.")
            time.sleep(2)
            print("[You]: I know she went outside because her shoes are in the garage but her sandals are missing.")
            time.sleep(2)
            print("[You]: Have you seen her? I need your help to find her.")
            time.sleep(2)
            print("[Qulsum]: Oh no! I haven't seen her today, but I will keep an eye out.")
            time.sleep(2)
            print("[Qulsum]: I will ask the neighbors if they have seen her. I will give you a call if I find anything.")
            time.sleep(2)
            print("[You]: Thank you! Miss, I really appreciate it.")
            time.sleep(2)
            print("With that, you say goodbye to Ms. Qulsum and continue searching the neighborhood.")
            time.sleep(2)
            search_neighborhood()

def search_neighborhood():
    print("You decide to search the neighborhood for your grandma.")
    time.sleep(2)
    print("You walk down the street, looking for any signs of her.  ")
    time.sleep(2)
    print("You see a few neighbors, but no one has seen her.")
    time.sleep(2)
    print("You decide to check the alley nearby, as she often goes there to relax.")
    time.sleep(2)   
    print("As you enter the alley, you notice a begger by the side of the road.")
    time.sleep(2)
    print("He looks up at you and asks for some change.")
    time.sleep(2)
    print("[Begger]: 'Spare some change, sir?")
    time.sleep(2)
    print("[You]: 'I am sorry, I don't have any change right now.")
    time.sleep(2)
    print("[You]: 'But I need your help. Have you seen my grandma? *Shows him a picture*.")
    time.sleep(2)
    print("[You]: 'She has been missing for a while and I am worried about her.")
    time.sleep(2)
    print("[Begger]: 'She... looks familiar... but some change might help jog my memory ;)")
    time.sleep(2)
    print("Agree to give him some change?")
    change_crisis()



def change_crisis():
    global cash
    user_input = input("Press Y to give him some change: ")
    if user_input == "Y":
        print("I need to get some money from the ATM.")
        time.sleep(2)
        print("[You]: I will be right back.")
        time.sleep(2)
        print("You head to the nearest ATM to withdraw some cash.")
        time.sleep(2)
        print("The ATM is closed for maintenance.")
        time.sleep(2)
        print("What to do now?")
        print("1. Go home and get money")
        print("2. Forget this beggar and continue searching")
        user_input = input("Choose 1 or 2: ")
        if user_input == "1":
            print("You decide to go home and get some money.")
            time.sleep(2)
            print("You head back home, feeling a bit defeated.")
            time.sleep(2)
            print("You take some cash from your drawer and head back to the alley.")
            time.sleep(2)
            beggar_talk()
            cash = 1000
        elif user_input == "2":
            print("You decide to forget about the beggar and continue searching.")
            time.sleep(2)
            print("You walk away, hoping to find your grandma elsewhere.")
            time.sleep(2)
            print("He probably didn't know anything anyway.")
            continue_searching()
        else:
            print("Invalid choice! Please choose 1 or 2.")
            change_crisis()

def beggar_talk():
    global cash

    print("You give the beggar some change.")
    time.sleep(2)
    print("[Beggar]: 'Thank you, sir.")
    time.sleep(2)
    print("[Beggar]: 'I think i i saw someone who looks like her... but I don't know for sure.")
    time.sleep(2)
    print("[Beggar]: 'I think I need some more change...")
    time.sleep(2)
    user_input = input("Press Y to give him more change or N to refuse: ")
    if user_input == "Y":
        print("You give the beggar more change.")
        time.sleep(2)
        print("[Beggar]: 'Thank you, sir. I need more...")
        time.sleep(2)
        print("You: 'I think you're lying to me. I don't have any more change.")
        time.sleep(2)
        print("[Beggar]: 'Please, sir.")
        time.sleep(2)
        print("You: 'Goodbye..")
        continue_searching()
    else:
        print("You refuse to give the beggar more change.")
        time.sleep(2)
        continue_searching()

def continue_searching():
    print("You decide to continue searching the neighborhood.")
    time.sleep(2)
    print("You walk down the street, looking for any signs of your grandma.")
    time.sleep(2)
    print("You see a decide to take a rest")
    time.sleep(2)
    print("You go to the neighborhood stall to buy a drink.")
    time.sleep(2)
    print("[You]: Hello sir, can I get a cold coke please?")    
    time.sleep(2)
    print("[Shopkeeper]: Sure, that will be 50 Taka.")
    time.sleep(2)
    print("[You]: thanks")
    time.sleep(2)
    print("You pay the shopkeeper and take a sip of your cold drink.")
    time.sleep(2)  
    print("As you take the sip, you notice a familiar necklace on the floor")  
    time.sleep(2)
    print("You pick it up and realize it's your grandma's necklace!")
    time.sleep(2)  
    print("[You]: Oh my goodness! This is my grandma's necklace!")
    time.sleep(2)
    print("[You]: Hello, sir, have you seen this person? *shows the picture*")
    time.sleep(2)
    print("[You]: It's my grandmother.. I need to find her, she is missing!")
    time.sleep(2)
    print("[Shopkeeper]: Yes! I have seen her. She was here a few hours ago.")
    time.sleep(2)
    print("[Shopkeeper]: She was looking for the directions to Shekhertek...")
    time.sleep(2)
    print("[You]: Shekhertek? That's where she used to live before moving here!")
    time.sleep(2)
    print("[You]: Thank you so much for your help, sir!")
    time.sleep(2)
    print("I must go to Shekhertek and find her!")